version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

services:
  easyng_apache_php:
    container_name: ${APACHE_HOST_NAME}
    build:
      context: .
      dockerfile: ./apache-php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        PROJECT_WORK_DIR: ${PROJECT_WORK_DIR_CONTAINER}
        APP_DIR_NAME: ${APP_DIR_NAME}
        TZ: ${TIMEZONE}
        APP_HOST: ${APP_HOST}
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        USER_NAME: ${USER_NAME}
        GROUP_NAME: ${GROUP_NAME}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ${PROJECT_WORK_DIR_HOST}:${PROJECT_WORK_DIR_CONTAINER}
    ports:
      - ${APACHE_HOST_HTTP_PORT}:80
      - ${APACHE_HOST_HTTPS_PORT}:443
    depends_on:
      - easyng_db
      - mailhog
    networks:
      backend:
        aliases:
          - ${APP_HOST}

  easyng_db:
    image: "mysql:${MYSQL_VERSION}"
    container_name: ${MYSQL_HOST_NAME}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${VALUES_PATH}/mysql:/var/lib/mysql
      - ${PROJECT_WORK_DIR_HOST}:${PROJECT_WORK_DIR_CONTAINER}
    networks:
      - backend

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - backend